import type { Metadata } from 'next';

import '../global.css';
import HeaderShop from '@/components/HeaderShop';
import ViewFormUser from '@/context/ViewFormUser';

export const metadata: Metadata = {
  title: 'Store',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewFormUser>
      <HeaderShop />
      {children}
    </ViewFormUser>
  );
}
