import type { Metadata } from 'next';

import './../globals.css';
import HeaderShop from '@/components/Header';

export const metadata: Metadata = {
  title: 'Beta cart shop',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="">
        <HeaderShop />
        {children}
      </body>
    </html>
  );
}
