import type { Metadata } from 'next';

import './globals.css';
import HeaderShop from '@/components/Header';
import { Bounce, ToastContainer } from 'react-toastify';

export const metadata: Metadata = {
  title: 'Store',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className="">
        <ToastContainer
          position="top-center"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
          transition={Bounce}
        />
        <HeaderShop />
        {children}
      </body>
    </html>
  );
}
